# -*- coding: utf-8 -*-
"""COVID 19 DATAS.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1trWCgDGWCzgTun6kzkGglbDonOI52Oks
"""

# COVID-19 Dataset

# Importing the necessary libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Importing the data
dataset = pd.read_csv('covid_19_data.csv')
dataset

#  Checking the head and tail of the data
dataset.head(3)

dataset.tail(3)

# Checking the null values
dataset.isnull().sum()

# Removing the state column
dataset.drop('State',axis=1,inplace=True)

dataset.sample(2)

# Looking at the basic information for the data
print(dataset.columns)
print()
print(dataset.shape) # 321 rows and 5 columns after removal
print()
print(dataset.info())
print()
print(dataset.describe())

# Using the datetime
dataset['Date'] = pd.to_datetime(dataset['Date'],dayfirst=False)
dataset['Month'] = dataset['Date'].dt.month_name()
dataset['Day'] = dataset['Date'].dt.day_name()
dataset['Year'] = dataset['Date'].dt.year

# Dropping the date column
dataset.drop('Date',axis =1,inplace=True)

dataset.sample(2)

# Checking the unique values
Regions = np.sort(dataset['Region'].unique())
print(f'The different regions in the dataset are: {Regions}')

# Creating a new columns mortality rate and recovery_rate
dataset['Mortality_Rate'] = (dataset['Deaths'] / dataset['Confirmed']) * 100
dataset['Recovery_Rate'] = (dataset['Recovered'] / dataset['Confirmed']) * 100
dataset.tail(2)

dataset.describe(include='object')

# Answering some questions

# Q.1) Which are the top 10 region that has the highest confirmed and death cases
Confirmed_cases = dataset.groupby('Region')['Confirmed'].sum().sort_values(ascending=False).head(10)
print(Confirmed_cases)
# From the data USA has the highest number of Confirmed cases followed by Spain and Italy

# For Deaths
Highest_deaths = dataset.groupby('Region')['Deaths'].sum().sort_values(ascending = False).head(10)
print(Highest_deaths)
# From the data,USA has the highest number of deaths followed by Italy and UK

# Which country has the highest recovery?
Highest_recovery = dataset.groupby('Region')['Recovered'].sum().sort_values(ascending = False).head(10)
print(Highest_recovery)
#  From the data given, Spain has the highest recovery followed by US and Germany

# Using matplotlib
# Top 10 countries in deaths
plt.figure(figsize=(10,5))
death = plt.bar(Highest_deaths.index,Highest_deaths.values,color ='Red')
plt.title('Top 10 Countries for Most Deaths')
plt.xlabel('Countries')
plt.ylabel('Deaths')
plt.show()

# For Confirmed
plt.figure(figsize=(10,5))
Confirmed = plt.barh(Confirmed_cases.index,Confirmed_cases.values,color = 'grey')
plt.title('Top 10 Countries For Most Confirmed Cases')
plt.xlabel('Countries')
plt.ylabel('Confirmed')
plt.show()

# Recovery
plt.figure(figsize=(10,5))
recovery = plt.bar(Highest_recovery.index,Highest_recovery.values,color = 'green')
plt.title('Top 10 Coutries For Most Recovered Cases')
plt.xlabel('Countries')
plt.ylabel('Recovered')
plt.show()



# correlation between confirmed and recovered
correlation1 = dataset[['Confirmed','Recovered']].corr()
print(correlation1)
# There is a positive relationship between confirmed and recovered.Countries having
# higher confirmed cases also have higher recovery cases.

# correlation between confirmed and deaths
correlation2 = dataset[['Confirmed','Deaths']].corr()
print(correlation2)
# There is a strong postivie correlation between confirmed cases and deaths. Countries
# that have higher case have higher number of deaths.

# Correlation between recovered and death
correlation3 = dataset[['Recovered','Deaths']].corr()
print(correlation3)
# There is a positive relationship between recovered and death.
# Countries that have high number of recoveries tends to have
# higher number of deaths.

# Use of Seaborn

pairplot = sns.pairplot(dataset[['Confirmed','Recovered','Deaths']])
pairplot

final_correlation = dataset[['Confirmed','Deaths','Recovered']].corr()
final_correlation

heatmap = sns.heatmap(final_correlation,vmin=0.5,vmax=1,annot=True)
print(heatmap)

"""FINAL INSIGHTS:


1.    On April 29, USA has the highest number of deaths and reported cases of COVID-19 followed by spain and Italy.

2.   Similarly, for the recovered cases Spain has the highest followed by US and Germany.

3. From this data we can know that in Spain there were high number of recoveries compared to other countries.

4. Although countries like Italy and UK fall under one of the highest
death and reported cases but in terms of recovery they are little behind.



"""

cleaned =dataset.to_csv('Cleaned COVID Dataset.csv')





































































