# -*- coding: utf-8 -*-
"""MARKETING CAMPAIGN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13hQGfKsWId8ejESrYZAvoVUr-YBFP3OS
"""

# Importing the Libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Importing the dataset
dataset = pd.read_csv('marketing_campaign_dataset.csv')

# Looking at the first 3 datas
dataset.head(3)

# Looking at the last 3 datas
dataset.tail(3)

# CHecking if there are any duplicted or not
print(dataset.duplicated().sum())
# No duplicates

# Checking if there are any null values or not
dataset.isnull().sum()
# Since there are no null values. Hence, the dataset is clean

# Basic information of datas

dataset.info()

dataset.columns

dataset.shape

dataset.describe()

# Using the datetime function
dataset['Date'] = pd.to_datetime(dataset['Date'],dayfirst = False)
dataset['Year'] = dataset['Date'].dt.year
dataset['Month'] = dataset['Date'].dt.month_name()
dataset['Day'] = dataset['Date'].dt.day_name()

# Changing the acquisition cost type to float
dataset['Acquisition_Cost'] = dataset['Acquisition_Cost'].str.replace('$','').str.replace(',','').astype(float)

# Removing the Date Column
dataset.drop('Date', axis = 1, inplace = True)

# Creating new columns Conversion_Rate_Percent and Click_Through_Rate
dataset['Conversion_Rate_Percent'] = dataset['Conversion_Rate'] * 100
dataset['Click_Through_Rate'] = (dataset['Clicks']/ dataset['Impressions']) * 100

dataset.drop('Conversion_Rate', axis = 1, inplace = True)

# Checking the unique Values
Company = dataset['Company'].unique()
print(f'The unique companies are:{Company}')

Campaign_Type = dataset['Campaign_Type'].unique()
print(f'The unique campaign types are:{Campaign_Type}')

Target_Audience = dataset['Target_Audience'].unique()
print(f'The unique target audiences are:{Target_Audience}')

Duration = dataset['Duration'].unique()
print(f'The different durations are: {Duration}')

Channel_Used = dataset['Channel_Used'].unique()
print(f'The different channels used are: {Channel_Used}')

Locations = dataset['Location'].unique()
print(f'The different locations are: {Locations}')

Languages = dataset['Language'].unique()
print(f'The different languages are: {Languages}')

Customer_Segments = dataset['Customer_Segment'].unique()
print(f'The different customer segments are: {Customer_Segments}')

# # n the city name one city was named N. Hence we wil replace this to New Jersey.
# dataset['Location'] = dataset['Location'].replace(['N'],['New Jersey'])

# In terms of Age there is all age so we will convert them to age not revealed.
dataset['Target_Audience'] = dataset['Target_Audience'].replace(['All Ages'],['Age Not Revealed'])

# Checking the information of datas apart from integers and float
dataset.describe(include = 'object')

#Questions to be solved

# 1) Which campaign has the highest ROI?
Highest_ROI = dataset.groupby('Campaign_Type')['ROI'].mean().sort_values(ascending = False)
print(Highest_ROI)
# Influencer campaign has the highest ROI followed by Search and Display

# 2) Which marketing channel performs the best in terms of ROI?
Best_Marketing_Channel = dataset.groupby('Channel_Used')['ROI'].mean().sort_values(ascending = False)
print(Best_Marketing_Channel)
# Facebook is the best marketing channel followed by Website and Google Ads

# 3) Which target auidence has the highest conversion rate?
Highest_Conversion_Rate = dataset.groupby('Target_Audience')['Conversion_Rate_Percent'].mean().sort_values(ascending = False)
print(Highest_Conversion_Rate)
# Men of age ranging between 18-24 has the hihest conversion rate

# 4) Which customer segment is more profitable?
Most_Profitable = dataset.groupby('Customer_Segment')['ROI'].mean().sort_values(ascending = False)
print(Most_Profitable)
# Foodies are the highest followed by Tech and Health

# 5) Which location deliveres the highest ROI?
Highest_ROI_Location = dataset.groupby('Location')['ROI'].mean().sort_values(ascending = False)
print(Highest_ROI_Location)
# Miami delivers the highest ROI followed by Los Angles and Houston

# 6) Which campaign has the highest engagement scores?
Highest_Engagement_Scores = dataset.groupby('Campaign_Type')['Engagement_Score'].mean().sort_values(ascending = False)
print(Highest_Engagement_Scores)
# Display has the highest engagement score followed by email and Social Media

# Visualization through Matplotlib

# Campaign with highest ROI
plt.figure(figsize = (10,5))
ROI = plt.bar(Highest_ROI.index, Highest_ROI.values, color = 'green')
plt.title('Campaigns With Highest ROI')
plt.xlabel('Campaigns')
plt.ylabel('ROI')
plt.show()

# Profitable customer segment
plt.figure(figsize = (10,5))
profitable = plt.barh(Most_Profitable.index, Most_Profitable.values, color = 'peru')
plt.title('Profitable Customer Segments')
plt.show()

# Locations with highest ROI
plt.figure(figsize = (10,5))
Highest_ROI_Locations = plt.bar(Highest_ROI_Location.index, Highest_ROI_Location.values, color = 'lightcoral')
plt.xlabel('Locations')
plt.ylabel('ROI')
plt.title('Highest ROI Locations')
plt.show()

# Campaign with Highest Engagement Scores
plt.figure(figsize = (10,5))
Engagement_Scores = plt.bar(Highest_Engagement_Scores.index, Highest_Engagement_Scores.values, color = 'dodgerblue')
plt.xlabel('Campaigns')
plt.ylabel('Engagement Scores')
plt.title('Highest Engagement Scores Campaigns')
plt.show()

# Use of boxplots for outliers
plt.boxplot(dataset['Conversion_Rate_Percent'])
plt.show()
# No Outliers

plt.boxplot(dataset['Click_Through_Rate'])
plt.show()
# The black dot shown are the outliers

# Finding Outliers
q1 = dataset['Click_Through_Rate'].quantile(0.25)
print(f'q1 is: {q1}')
q3 = dataset['Click_Through_Rate'].quantile(0.75)
print(f'q3 is: {q3}')
IQR = q3 - q1
print(f'The IQR is: {IQR}')
Lower_bound = q1 - 1.5 * IQR
print(f'The lower bound is: {Lower_bound}')
Upper_bound = q3 + 1.5 * IQR
print(f'The upper bound is: {Upper_bound}')
Outliers = dataset[(dataset['Click_Through_Rate'] < Lower_bound) | (dataset['Click_Through_Rate'] > Upper_bound)]
print(f'The outliers are: {Outliers}')
print(len(Outliers))

# Use of seaborn

# Conversion rate vs ROI
correlation_1 = dataset[['Conversion_Rate_Percent','ROI']].corr()
print(correlation_1)
# There is almost no relationship between Conversion rate and ROI.
# This means Conversion rate does not necessarily result in increase in ROI.

# Engagement Score vs ROI
correlation_2 = dataset[['Engagement_Score','ROI']].corr()
print(correlation_2)
# There is a little positive relation between them.
# This shows Higher engagement score does not necessarily lead to increase in ROI.

# Clicks vs Conversion Rate
correlation_3 = dataset[['Clicks', 'Conversion_Rate_Percent']].corr()
print(correlation_3)
# The relationship between them is close to zero.
# This shows that increase in the clicks does not directly lead to increase in Conversion

pairplot = sns.pairplot(dataset[['Conversion_Rate_Percent','ROI','Engagement_Score','Clicks']])
print(pairplot)

merged_correlation = dataset[['Conversion_Rate_Percent','ROI','Engagement_Score','Clicks']].corr()
print(merged_correlation)

sns.heatmap(merged_correlation, vmin = -1, vmax = 1, annot = True)



"""FINAL COMMENTS


1. The campaign done through the influencers resulted in high ROI (5.011) in average followed by Search(5.008) and Display(5.006). This shows that people tend to use the products advertised by the influencers.

2. Facebook performed the best in terms of average ROI (5.018) followed by Websites (5.014) and Gogle Ads (5.003). This shows that Facebook is considered the best marketplace for marketing campaign since it is used by people of all age.

3. Men aged between 18-24 had the highest conversion rate (8.023) at Food related products (5.0043). This gives the insights that businesses should mainly target the food products in marketing which are favoured by men aged betwee 18-24.

4. Miami generates the highest ROI (5.012). Since, Miami is a tourist spot so the marketing campaign done on Miami goves higher ROI.

5. There is almost no relationship between Conversion rate and ROI(-0.001).This means Conversion rate does not necessarily result in increase in ROI.

6. There is a little positive relation between Engagement Score and  ROI (0.00058).This shows Higher engagement score does not necessarily lead to increase in ROI.

7. The relationship between them is close to zero (0.000269).
This shows that increase in the clicks does not directly lead to increase in Conversion.

LIMITATIONS

1. The only limitation of this dataset is that it is fictional and not real. Hence that is the reason why the relationship shown between different segments migt not be satisfactory. Also, the difference in ranking between different segments is very little due to the fictional data.
"""

dataset.to_csv('Cleaned_Marketing.csv')



























