# -*- coding: utf-8 -*-
"""Multiple restaurants sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/17SOaV7j5L1BtU5z1AO-QLyrHUfyV0IBe
"""

# Project on restaurant companies operating in different countries

# WE will be importing some needed libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# After that we will import the dataset that is required
dataset = pd.read_csv('9. Sales-Data-Analysis.csv')
dataset

# We will see the first five and last five from the given dataset
dataset.head(5)

dataset.tail(5)

# Now we will check if there are any null values present or not
dataset.isnull().sum()
# Since there are no null values which means the values are filled

# Now checking whether there are any duplicated rows or not
print(dataset.duplicated().sum())
# Hence there are no duplicates prsent

# Now we will be seeing some basoc and statistical information of the dataset
print(dataset.columns)
print()
print(dataset.info())
print()
print(dataset.shape) # There are 254 rows and 9 columns
print()
print(dataset.describe())

# Since the quantity is in float hence we will convert them to integer for simplicity
dataset['Quantity'] = dataset['Quantity'].astype(int)

dataset

# Using the datetime
dataset['Date'] = pd.to_datetime(dataset['Date'],dayfirst=True)
dataset['Day'] = dataset['Date'].dt.day_name()
dataset['Month'] = dataset['Date'].dt.month_name()
dataset['Year'] = dataset['Date'].dt.year
dataset

# SInce it has been speararted now we will remove the date column permanently
dataset.drop('Date',axis =1, inplace = True)

dataset

print(dataset.info())

# We will replace the credit card to card payment in Payment Method
dataset['Payment Method'] = dataset['Payment Method'].str.strip().replace(['Credit Card'],['Card Payment'])
dataset['Payment Method']

# Removing unwanted spaces from all dataset
dataset['Product'] = dataset['Product'].str.strip()
dataset['Purchase Type'] = dataset['Purchase Type'].str.strip()
dataset['Manager'] = dataset['Manager'].str.strip().str.replace(r'\s+', ' ', regex=True)
dataset['City'] = dataset['City'].str.strip()

# Checking the unique values in dataset for further analysis
Products = dataset['Product'].unique()
print(f' The different products are: {Products}')
print()
print()
print()
Prices = np.sort(dataset['Price'].unique())
print(f' The different Prices are: {Prices}')
print()
print()
print()
Purchase_type = dataset['Purchase Type'].unique()
print(f' The different purchasing types are: {Purchase_type}')
print()
print()
print()
Payment_method = dataset['Payment Method'].unique()
print(f' The different ways of payments are: {Payment_method}')
print()
print()
print()
Manager_names = dataset['Manager'].unique()
print(f' The different manager names are: {Manager_names}')
print()
print()
print()
City_names = dataset['City'].unique()
print(f' The different city names are: {City_names}')
print()
print()
print()
Years = dataset['Year'].unique()
print(f' The years mentioned in the dataset are: {Years}')
print()
print()
print()
Months = dataset['Month'].unique()
print(f'The months in the dataset are: {Months}')

dataset.describe(include = 'object')

# Solving some basic questions

# Q.1) Most Preferred Payment Method ?
Preferred_payment_method = dataset['Payment Method'].value_counts()
print(Preferred_payment_method)
# The most preferred payment method is Card Payment followed by Cash

# Q.2) Most Selling Product - By Quantity & By Revenue ?
Most_selling_product = dataset.groupby('Product')['Quantity'].sum().sort_values(ascending = False)
print(Most_selling_product)
# The most sold product is Beverages followed by Fries and Burgers

# Since there was no column to calculate revenue hence we created a new column named revenue
dataset['Revenue'] = dataset['Price'] * dataset['Quantity']
dataset

By_revenue = dataset.groupby('Product')['Revenue'].sum().sort_values(ascending = False)
print(By_revenue)
# By revenue most sold product is Burger

# Q.3) Which city had maximum revenue , or , Which Manager earned maximum revenue ?
dataset['Manager'].str.strip()
max_rev_city = dataset.groupby('City')['Revenue'].sum().sort_values(ascending=False)
print(max_rev_city)
print()
print()
print()
max_rev = dataset.groupby('Manager')['Revenue'].sum()
print(max_rev)

# From the above data we can see Lisbon had the maximum revenue earned by Joao Silva

# Q.4) Average Revenue.
average_revenue = dataset['Revenue'].mean()
print(average_revenue)
# The average revenue of two months was 3026.89

# Q.5) Average Revenue of November & December month.
average_revenue_months = dataset.groupby('Month')['Revenue'].mean().sort_values()
print(average_revenue_months)
# Average revenue for Nov was 2936.65
# Average revenue for Dec was 3099.21

# Q.6) Is revenue increasing or decreasing over time?
Revenue_nov = dataset[dataset['Month']== 'November']['Revenue'].sum()
print(Revenue_nov)
print()
print()
print()
Revenue_dec = dataset[dataset['Month']=='December']['Revenue'].sum()
print(Revenue_dec)
# Based on the result the revenue is increasing.

# Q.7) Average 'Quantity Sold' & 'Average Revenue' for each product ?
avg_quantity_sold = dataset.groupby('Product')['Quantity'].mean().sort_values(ascending= False)
print(avg_quantity_sold)
print()
print()
print()
avg_revenue = dataset.groupby('Product')['Revenue'].mean().sort_values(ascending = False)
print(avg_revenue)
 # Beverages were the most sold in avg but revenue comes from burgers

# Q.8) Expensive and chepest product
price = dataset.groupby('Product')['Price'].max().sort_values(ascending=False)
print(price)
# Chicken Sandwiches are the expensive and Beverages are cheapest.

# Q.9) Which city sells the most and least
most_sold_city = dataset['City'].value_counts()
print(most_sold_city)
# London is the most sold equalling Lisbon and Paris is the least sold.

# Q. 10) Most and least purchasing type
most_purchase_type = dataset['Purchase Type'].value_counts()
print(most_purchase_type)
# People mostly order through online.

# Visualization through matplotlib

dataset

# Most Preferred Transaction Type
plt.figure(figsize=(8,8))
transaction_type_counts = dataset['Purchase Type'].value_counts()
pie_chart = plt.pie(transaction_type_counts, labels = transaction_type_counts.index,autopct='%1.1f%%', startangle = 90,colors = ['goldenrod','cornsilk','tan'])
plt.title('Most Preferred Transaction Type')
plt.show()
# Most preferred transaction type is Online followed by In store purchases.
# This means people usually order through their home and offices.

# Most selling product by quantity
plt.figure(figsize=(10,5))
bar_graph = plt.bar(Most_selling_product.index, Most_selling_product.values, color='brown')
plt.title('Most Selling Product by Quantity')
plt.xlabel('Product')
plt.ylabel('Quantity')
plt.show()
# The most sold product by quantity is beverages. It may be due to its low cost as it is cheap.
# This means people usually prefer cheap goods.

# By revenue
plt.figure(figsize = (10,5))
h_bar = plt.barh(By_revenue.index, By_revenue.values, color = 'tan')
plt.title('Most Selling Products By Revenue')
plt.show()
# Although beverages were the most sold in quantity but burgers give the most revenue followed by fries
# It may be due to the median price of burger.
# and Chicken sandwiches. Due ot the low price of beverages although they are most sold in quantity
# but still revenue is not generated enough.

# Expensie and Cheap Products
plt.figure(figsize=(10,5))
bar_graph = plt.bar(price.index,price.values, color = 'tomato')
plt.title('Price of Products')
plt.xlabel('Products')
plt.ylabel('Price')
plt.show()
# Chicken Sandwiches are the expensive products and Beverages are the cheapest.

# Boxplot for quantity
plt.boxplot(dataset['Quantity'])
plt.show()
# No outliers

# For revenue
plt.boxplot(dataset['Revenue'])
plt.show()
# The dot shown are the outliers

# Here IQR is used for outliers
q1 = dataset['Revenue'].quantile(0.25)
print(f' q1 is:{q1}')
q3 = dataset['Revenue'].quantile(0.75)
print(f'q3 is:{q3}')
IQR = q3 - q1
print(f'The IQR is: {IQR}')
lower_bound = q1 - 1.5 * IQR
print(f'Lower Bound is: {lower_bound}')
upper_bound = q3 + 1.5 * IQR
print(f'Upper bound is: {upper_bound}')
outliers = dataset[(dataset['Revenue']< lower_bound) | (dataset['Revenue']> upper_bound)]
print(f' The outliers are: {outliers}')
print(len(outliers))

# For correlation
correlation1 = dataset[['Price','Quantity']].corr()
print(correlation1)
# There is a negative correlation which means higher priced goods leads to decrease in quantitiy.

# For correlation
correlation2 = dataset[['Quantity','Revenue']].corr()
print(correlation2)
# Positive as when quantity increases revenue increases

# For correlation
correlation3 = dataset[['Price','Revenue']].corr()
print(correlation3)
# Positive relation as the higher prices goods give high revenue.

pairplot = sns.pairplot(dataset[['Price','Quantity','Revenue']])
print(pairplot)

# Heatmap for Price and Quantity
sns.heatmap(correlation1, vmin =-1, vmax=1,annot = True)

# Revenue and Quantity
sns.heatmap(correlation2, vmin = -1, vmax= 1, annot = True)

# Revenue and Price
sns.heatmap(correlation3, vmin =-1, vmax=1, annot= True)

merged_correlation = dataset[['Quantity','Price','Revenue']].corr()
print(merged_correlation)

sns.heatmap(merged_correlation,vmin = -1, vmax =1 , annot = True)

"""FINAL INSIGHTS:
1. Most preferred transaction type is Online followed by In store purchases.This means business should focus more on improving their online deliveries for their customers convenience.

2. Beverages sells the most in quantitiy due to its low price but generates low revenue. Similarly, Burgers and Fries are mostly favored by the people due to their balanced price as the generate hiigher reveune and are also one of the most sold products.

3. Chicken Sandwiches are sold less in quantities due to their higher prices. Since quantitiy and price shows the negative relationship therefore if the restsurant can experiment by lowering the prcies that could increase their selling quantity and generate more revenue.

"""

cleaned_dataset = dataset.to_csv('Cleaned Multiple Restaurant Data.csv')



















































































