# -*- coding: utf-8 -*-
"""Self project restaurant sales5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/177WW8qRpRyTMUVf0r3wtuo2NUOzYcFY8
"""

# First project on restaurant sales
# The data are from year 2022 and 2023
# There are 9 months in this data for year 2022 from April to December
# There are 3 months in this data for year 2023 from Jan to Mar

# First we will be importing some basic tools needed for this project
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

# Importing the restaurant dataset and viewing it
dataset = pd.read_csv('Balaji Fast Food Sales.csv')
dataset

# Viewing the first 10 and last 10 datas using head and tail
head = dataset.head(10)
head

tail = dataset.tail(10)
tail

# Basic information for the data
print(dataset.columns)
print()
print()
print()
print(dataset.shape) # It has 1000 rows and 10 columns
print()
print()
print()
print(dataset.info())
print()
print()
print()
print(dataset.describe())

# After this we will be checking if there are any null values or not
dataset.isnull().sum()
# There are 107 null values in the transaction type
# Since there are many so we will be replacing them instead of removing it

# Refilling the null values in transaction type
dataset['transaction_type'] = dataset['transaction_type'].fillna('Card Payment')
# The null values in transaction type were filled by card payment

dataset

# Checking the different values and amounts mentione din the whole dataset
print(f'The transaction types are:{dataset['transaction_type'].unique()}')
print()
print()
print()
print(f"The item name are:{dataset['item_name'].unique()}")
print()
print()
print()
print(f'The item types are:{dataset['item_type'].unique()}')
print()
print()
print()
print(f'The item prices are:{dataset['item_price'].unique()}')
print()
print()
print()
print(f'The item quantities are:{dataset['quantity'].unique()}')
print()
print()
print()
print(f'The transaction amounts are:{dataset['transaction_amount'].unique()}')
print()
print()
print()
print(f'The time of sale are:{dataset['time_of_sale'].unique()}')

# After refilling the null values we will be agai checking if there are any null values or not
dataset.isnull().sum()
# There are no null values now we can further continue to other things

# Now we will be separating the date month and year to different columns
# We will first replace '-' with '/'
dataset['date'] = dataset['date'].str.replace('-','/')
dataset['date']

dataset['Month'] = dataset['date'].str.split('/').str[0]
dataset['Day'] = dataset['date'].str.split('/').str[1]
dataset['Year'] = dataset['date'].str.split('/').str[2]
dataset

# After separating the month,day and year we will be removing the date column
dataset = dataset.drop('date', axis=1)
dataset

# Since the day month and year are in object we will convert them into integer
print(dataset['Day'].dtype)

dataset['Day'] = dataset['Day'].astype(int)
dataset['Month'] = dataset['Month'].astype(int)
dataset['Year'] = dataset['Year'].astype(int)
print(dataset['Day'].dtype)

# For further simplicity of data we replaced Mr and Mrs with Male and Female
dataset['received_by'] = dataset['received_by'].replace(['Mr.'],['Male'])
dataset['received_by'] = dataset['received_by'].replace(['Mrs.'],['Female'])
dataset['received_by']

# We will be seeing the years and months on the data and provide the information above
months_2023_data = dataset[dataset['Year']==2023]['Month'].unique()
print(f'The total months in the year 2023 are:{np.sort(months_2023_data)}')
print()
print()
print()
months_2022_data = dataset[dataset['Year']==2022]['Month'].unique()
print(f'The total months in the year 2022 are:{np.sort(months_2022_data)}')

dataset
# Since the data is now cleaned and clear, we will be solving some basic questions through pandas

dataset.describe(include = 'object')

# 1) Which is most purchased item and least purchased item?
most_purchased = dataset['item_name'].value_counts()
print(most_purchased)
# The most purchased items is Cold Coffee followed by Sugarcane Juice and Panipuri
# The least purchased item is Sandwich

# 2) What are the most type of transaction_types?
transaction_type = dataset['transaction_type'].value_counts()
print(transaction_type)
# The most used transaction type is through Cash
# The least used transaction type is Card Payment

# 3) Which gender orders the most?
order = dataset['received_by'].value_counts()
print(order)
# The orders are mostly ordered by male

# 4) What is most time of sale?
sale = dataset['time_of_sale'].value_counts()
print(sale)
# Most time of sale is on Night followed by Afternoon and Evening
# Least sales happens on Morning

# 5) Which are most and least expensive items?
expensive_item = dataset['item_price'].max()
print(expensive_item)
print()
print()
print()
expensive_item_row = dataset[dataset['item_price']== expensive_item]
print(expensive_item_row)
# Sandwich is the most expensive which costs Rs 60

least_expensive = dataset['item_price'].min()
print(least_expensive)
print()
print()
print()
least_expensive_row = dataset[dataset['item_price']== least_expensive]
print(least_expensive_row)
# Aalopuri and Vadapav and Panipuri are least expensive which costs Rs 20

year_sales1 = dataset[dataset['Year']==2022]['transaction_amount'].sum()
year_sales2 = dataset[dataset['Year']==2023]['transaction_amount'].sum()
print(f'The total sales in 2022 is:{year_sales1}')
print(f'The total sales in 2023 is:{year_sales2}')

# Least sales were made in year 2023

dataset

# 7) Average spent by male and female
average_spent = dataset.groupby('received_by')['transaction_amount'].mean()
print(average_spent)
# Average Spent by male is Rs 270 and Female is Rs 280

# We will now move to visualizations on Matplotlib and Seaborn

plt.figure(figsize=(10,5))
bar_graph = plt.bar(dataset['item_name'],dataset['item_price'])
plt.title('Products and Price')
plt.xlabel('Products')
plt.ylabel('Price')
plt.show()

"""Most expensive Sandwich at Rs 60  followed by Frankie at Rs 50 and Cold Coffee at Rs 40. Aalopuri, Vadapav and Panipuri are priced same at Rs 20. Similarly, Sugarcane is priced at Rs 30"""

item_type_counts = dataset['item_type'].value_counts()
plt.figure(figsize=(8, 8))
plt.pie(item_type_counts, labels=item_type_counts.index, autopct='%1.1f%%', startangle = 90)
plt.title('Distribution of Item Types')
plt.show()

"""From the pie chart we can see Distribution of Fastfood is higher with 68.6% when compared to Bevrages which is 31.4%. This means Fastfood are sold more than Bevrages."""

dataset

often_ordered = dataset.groupby('item_name')['quantity'].sum().sort_values()
print(often_ordered)

plt.figure(figsize = (10,5))
hbar_graph = plt.barh(often_ordered.index,often_ordered.values)
plt.title('Most Often Ordered Items')



"""Cold Coffee is most ordered with 1361 times followed by Sugarcane Juice and Panipuri. Although, Vadapav and Aalopuri are least expensive but still they are ordered less.

"""

# Total revenue of the products
total_revenue = dataset.groupby('item_name')['transaction_amount'].sum().sort_values()
print(total_revenue)

plt.figure(figsize = (10,5))
hbar_graph2 = plt.barh(total_revenue.index,total_revenue.values)
plt.title('Total Revenue by Products')



"""Although the price of Sandwich is higher but still it is the highest revenue generator. Similar goes with Frankie and Cold Coffee. Whereas cheap items like Vadapav, Aalopuri,Panipuri are lowest revenue generator. The major difference might be due to price but still all the expensive items are at the top.

"""

# For transaction type
item_counts = dataset['transaction_type'].value_counts()
plt.figure(figsize = (8,8))
plt.pie(item_counts.values,labels = item_counts.index,autopct='%1.1f%%',startangle = 90)
plt.title('Transaction Types')



"""Most of the transaction are done through cash which is 47.6% followed by online which is 41.7%. Similarly, people are not always interested in paying through cards."""

# For time of sale
item_counts = dataset['time_of_sale'].value_counts()
plt.figure(figsize = (8,8))
plt.pie(item_counts.values,labels = item_counts.index, autopct='%1.1f%%',startangle = 90)
plt.title('Time of Sale')



"""Most of the sales are made in Afternoon and Night whereas least sales are made in Morning followed by Midnight

"""

# Customers
plt.figure(figsize = (8,8))
item_counts = dataset['received_by'].value_counts()
plt.pie(item_counts.values, labels = item_counts.index, autopct= '%1.1f%%',startangle = 90)
plt.title('Customers Distribution')



"""The Customer distribution seems to be almost equal between Male and Female."""

dataset.to_csv('Balaji Fast Food Sales Cleaned.csv')



































































